### PR TITLE
modernise with an alienfile

### LINKED ISSUE #5: `gsl-config --prefix` Wrongly Returns "~/.cpanm/work" Temp Directory
After I have successfully installed Alien::GSL, I should be able to call `gsl-config --prefix` and have it return the exact same value as Alien::GSL->dist_dir(), however it is incorrectly returning a temporary work directory used by CPANM during build & installation...

CORRECT RETURN VALUE:
```
    $ perl -e 'use Alien::GSL; print Alien::GSL->dist_dir(), "\n";'
    /home/foo_user/perl5/lib/perl5/auto/share/dist/Alien-GSL
```

INCORRECT RETURN VALUE:
```
    $ perl -e 'use Alien::GSL; use Env qw(@PATH); unshift @PATH, Alien::GSL->bin_dir(); print `gsl-config --prefix`;'
    /home/foo_user/.cpanm/work/foo_serial/Alien-GSL-1.01/blib/lib/auto/share/dist/Alien-GSL
```

This causes a potential downstream error in Math::GSL because I am in the process of adding Alien::GSL support but Math::GSL wants to call `gsl-config --prefix`:

https://github.com/leto/math--gsl/blob/master/Build.PL#L321

[[[ UPDATED: system install info ]]]

It is not correct to replace `gsl-config --prefix` with Alien::GSL->dist_dir() because in a system install of GSL the value of bin_dir() is empty and calling dist_dir() actually gives an error:

```
    $ perl -e 'use Alien::GSL; print Alien::GSL->dist_dir(), "\n";'
    Failed to find share dir for dist 'Alien-GSL' at -e line 1.
```

Anyway, we should not be having a patently incorrect value returned by `gsl-config --prefix` because it could cause other unknown future errors in addition to this example.

I do not understand the internals of Alien whatsoever, so I apologize that I do not have a pull request to fix this issue, although I will be more than happy to assist in reaching a solution in any way I can.  Thanks in advance!

:-)

### PR DESCRIPTION
**Pull request by kiwiroy**
The `AB::MB` has been translated to an `alienfile` and `dist.ini` - the latter might be deficient. Might well resolve #5 as discussed there. Travis tooling might be deficient too - time for gh actions?

This incorporates the change to https also.

### CODE REVIEW

**Comment by jberger** [comment]
I am interested in moving to alienfile, I'm even ok with moving to EUMM, but I'm rather irascibly opposed to dzil. Any chance you could port it a little less?

**Comment by kiwiroy** [comment]
@jberger understood. ~200 modules is a little heavy deps wise.

**Comment by plicease** [comment]
EUMM and MB sans dzil are both fully supported via `Alien::Build::MM` and `::MB` (the latter has extra prereqs)

**Comment by zmughal** [comment]
Freshening up this PR is just a matter of copying the `.PL` file out of the `dzil build` directory, right?

**Comment by hakonhagland** [comment]
See also [this](https://github.com/leto/math--gsl/issues/221) in `Math::GSL`. I have tested this PR and compared with the master branch, and it seems to me that this will fix #5. The problem with the master branch regarding issue #5 is that it uses `Alien::Base::ModuleBuild` which builds GSL in the local build directory (or in the `cpanm` work directory) and then copies the built libraries to the dist directory. This is not the correct approach since the `gsl-config` script a hardcoded prefix from the place where it was built (`configure --prefix=...`). On the other hand, this PR works well since Dist::Zilla to creates a `Makefile.PL` that uses `Alien::Build::MM` which compiles GSL in the dist directory instead.

> I'm rather irascibly opposed to dzil

@jberger I am starting to like `Dist:Zilla`. It took me some time to learn though. And of course it is only author dependency, the user of the module does not have to install `Dist::Zilla`. 

> Freshening up this PR is just a matter of copying the .PL file out of the dzil build directory, right?

@zmughal Yes I think so. @jberger  I have submitted a new PR #8 based on this that does not use `Dist::Zilla`, you may decide if you would use this or  #8

**Comment by plicease** [comment]
closing in favor of some refinement of #8

**Pull request closed without merging**
